from collections import OrderedDict

glyphicons = ["asterisk", "plus", "euro", "minus", "cloud", "envelope", "pencil", "glass", "music", "search", "heart", "star", "star-empty", "user", "film", "th-large", "th", "th-list", "ok", "remove", "zoom-in", "zoom-out", "off", "signal", "cog", "trash", "home", "file", "time", "road", "download-alt", "download", "upload", "inbox", "play-circle", "repeat", "refresh", "list-alt", "lock", "flag", "headphones", "volume-off", "volume-down", "volume-up", "qrcode", "barcode", "tag", "tags", "book", "bookmark", "print", "camera", "font", "bold", "italic", "text-height", "text-width", "align-left", "align-center", "align-right", "align-justify", "list", "indent-left", "indent-right", "facetime-video", "picture", "map-marker", "adjust", "tint", "edit", "share", "check", "move", "step-backward", "fast-backward", "backward", "play", "pause", "stop", "forward", "fast-forward", "step-forward", "eject", "chevron-left", "chevron-right", "plus-sign", "minus-sign", "remove-sign", "ok-sign", "question-sign", "info-sign", "screenshot", "remove-circle", "ok-circle", "ban-circle", "arrow-left", "arrow-right", "arrow-up", "arrow-down", "share-alt", "resize-full", "resize-small", "exclamation-sign", "gift", "leaf", "fire", "eye-open", "eye-close", "warning-sign", "plane", "calendar", "random", "comment", "magnet", "chevron-up", "chevron-down", "retweet", "shopping-cart", "folder-close", "folder-open", "resize-vertical", "resize-horizontal", "hdd", "bullhorn", "bell", "certificate", "thumbs-up", "thumbs-down", "hand-right", "hand-left", "hand-up", "hand-down", "circle-arrow-right", "circle-arrow-left", "circle-arrow-up", "circle-arrow-down", "globe", "wrench", "tasks", "filter", "briefcase", "fullscreen", "dashboard", "paperclip", "heart-empty", "link", "phone", "pushpin", "usd", "gbp", "sort", "sort-by-alphabet", "sort-by-alphabet-alt", "sort-by-order", "sort-by-order-alt", "sort-by-attributes", "sort-by-attributes-alt", "unchecked", "expand", "collapse-down", "collapse-up", "log-in", "flash", "log-out", "new-window", "record", "save", "open", "saved", "import", "export", "send", "floppy-disk", "floppy-saved", "floppy-remove", "floppy-save", "floppy-open", "credit-card", "transfer", "cutlery", "header", "compressed", "earphone", "phone-alt", "tower", "stats", "sd-video", "hd-video", "subtitles", "sound-stereo", "sound-dolby", "sound-5-1", "sound-6-1", "sound-7-1", "copyright-mark", "registration-mark", "cloud-download", "cloud-upload", "tree-conifer", "tree-deciduous"]

weather_icons = OrderedDict()

weather_icons['Day / Sunny'] = ["day-cloudy-gusts", "day-cloudy-windy", "day-cloudy", "day-fog", "day-hail", "day-lightning", "day-rain-mix", "day-rain-wind", "day-rain", "day-showers", "day-snow", "day-sprinkle", "day-sunny-overcast", "day-sunny", "day-storm-showers", "day-thunderstorm"]

weather_icons['Neutral / Cloudy'] = ["cloudy-gusts", "cloudy-windy", "cloudy", "fog", "hail", "lightning", "rain-mix", "rain-wind", "rain", "showers", "snow", "sprinkle", "storm-showers", "thunderstorm", "windy"]

weather_icons['Night / Moons'] = ["night-alt-cloudy-gusts", "night-alt-cloudy-windy", "night-alt-hail", "night-alt-lightning", "night-alt-rain-mix", "night-alt-rain-wind", "night-alt-rain", "night-alt-showers", "night-alt-snow", "night-alt-sprinkle", "night-alt-storm-showers", "night-alt-thunderstorm", "night-clear", "night-cloudy-gusts", "night-cloudy-windy", "night-cloudy", "night-hail", "night-lightning", "night-rain-mix", "night-rain-wind", "night-rain", "night-showers", "night-snow", "night-sprinkle", "night-storm-showers", "night-thunderstorm"]

weather_icons['Miscellaneous Weather'] = ["celcius", "cloud-down", "cloud-refresh", "cloud-up", "cloud", "degrees", "down-left", "down", "fahrenheit", "horizon-alt", "horizon", "left", "lightning", "night-fog", "refresh-alt", "refresh", "right", "sprinkles", "strong-wind", "sunrise", "sunset", "thermometer-exterior", "thermometer-internal", "thermometer", "tornado", "up-right", "up", "wind-east", "wind-north-east", "wind-north-west", "wind-north", "wind-south-east", "wind-south-west", "wind-south", "wind-west"]
